name: trailbase_benchmark
description: A simple benchmark in dart.
version: 0.0.1

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  trailbase:
    path: ../../../trailbase/client/trailbase-dart
  pool: ^1.5.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
