name: trailbase_benchmark
description: A simple benchmark in dart.
version: 0.0.1

environment:
  sdk: ^3.5.3

dependencies:
  trailbase: ^0.3.0
  pool: ^1.5.1
  dio: ^5.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
