[package]
name = "trailbase_benchmark_runner_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
reqwest = "0.12.5"
serde = { version = "^1.0.204", features = ["derive"] }
serde_json = "1.0.120"
tokio = {version  = "^1.38.0", features=["macros", "rt-multi-thread"] }
